export const ENABLE_LOADER = 'ENABLE_LOADER'
export const DISABLE_LOADER = 'DISABLE_LOADER'

// story
export const STORY_INIT = 'STORY_INIT'
export const STORY_ENABLE = 'STORY_ENABLE'
export const STORY_UPDATE_DESCRIPTION = 'STORY_UPDATE_DESCRIPTION'
export const STORY_DISABLE = 'STORY_DISABLE'
export const STORY_REVEAL = 'STORY_REVEAL'
export const STORY_RESET = 'STORY_RESET'
export const STORY_INIT_RESET_FLAG = 'STORY_INIT_RESET_FLAG'

// USERS
export const USER_INIT = 'USER_INIT'
export const USER_CHANGE_USERNAME = 'USER_CHANGE_USERNAME'
export const USER_VOTED = 'USER_VOTED'

// CARDS
export const CARDS_RESET_TOGGLE = 'CARDS_RESET_TOGGLE'
